### ISSUE TITLE
User name is wrong on Readme

### ISSUE THREAD

**Issue by erikn69** [aliqasemzadeh/bap#1]
https://github.com/alighasemzadeh/bap/blob/8b4ae1c10d17b184a664c459cb4132e51d40209c/database/seeders/UserSeeder.php#L20
https://github.com/alighasemzadeh/bap/blob/8b4ae1c10d17b184a664c459cb4132e51d40209c/README.md#L38
Must be `info@bap.local`, not `info@bal.local`

**Comment by aliqasemzadeh** [comment]
Hi
Thanks.

Fixed: https://github.com/alighasemzadeh/bap/commit/5119a5fd840a636a9f226bde5fc8bbc32b438c36
