### ISSUE TITLE
why the page is upside down

### ISSUE THREAD

**Issue by kaideng-nmg** [aliqasemzadeh/bap#3]
![image](https://user-images.githubusercontent.com/40782150/151478608-6883dc74-1ece-4d87-9bf3-ad22b3102ed6.png)

**Comment by aliqasemzadeh** [comment]
Can you heighlight parts ?

**Comment by kaideng-nmg** [comment]
![image](https://user-images.githubusercontent.com/40782150/152941765-98473a61-c01b-4b99-bf8c-375401b26195.png)
all item is upside down

**Comment by aliqasemzadeh** [comment]
Do you want to change font size?
Did you check tabler/tabler template?
