### ISSUE TITLE
Swiftmailer error on install and login

### ISSUE THREAD

**Issue by xnasa** [aliqasemzadeh/bap#4]
I did a fresh install. set up the database. published the tables. installed the npm. then ran PHP artisan serve.  the site is available but upon login with the credentials provided I get the following error.

Swift_TransportException
Connection could not be established with host mailhog :stream_socket_client(): php_network_getaddresses: getaddrinfo failed: No such host is known.

with no setup instructions for swiftmailer (and its depreciation) I'm not sure what to do next to view your project.

**Comment by aliqasemzadeh** [comment]
Hi
We use auth log in this package.
https://github.com/alighasemzadeh/bap/blob/99632b350568ed3ad3a892fc49ae5b1684916e55/app/Models/User.php#L25
And you have to config mail server.
Then please register in mailtrap.io and edit your information in `.env`
