### ISSUE TITLE
How to login on specific team when teams are enabled? 

### ISSUE THREAD

**Issue by systemsolutionweb** [aliqasemzadeh/bap#6]

**Comment by aliqasemzadeh** [comment]
Hi @systemsolutionweb 
I am working on team and team permissions new version on way.

**Comment by systemsolutionweb** [comment]
https://github.com/spatie/laravel-permission/discussions/2075
Also how to get back `team_id` on remember me functionality?

Recaller doesn't allow customs extra values
https://github.com/laravel/framework/blob/b9203fca96960ef9cd8860cb4ec99d1279353a8d/src/Illuminate/Auth/Recaller.php
https://github.com/laravel/framework/blob/b9203fca96960ef9cd8860cb4ec99d1279353a8d/src/Illuminate/Auth/Recaller.php#L80-L85

**Comment by aliqasemzadeh** [comment]
@systemsolutionweb 
Before any thing we need team management in admin panel in user management.
After that we assign permission to teams.
![image](https://user-images.githubusercontent.com/26847446/164705266-2a6fc727-e201-4987-a221-8265a81a6387.png)
I will add teams in admin panel and permission  and role can be assigned to it.

**Comment by erikn69** [comment]
> Also how to get back team_id on remember me functionality?

You can add a cookie

**Comment by erikn69** [comment]
>Also how to get back team_id on remember me functionality?

Maybe this helps on laravel 9.x for "remember me" functionality 
https://github.com/laravel/framework/pull/42316
https://github.com/laravel/framework/pull/42615

**Comment by parallels999** [comment]
Hi @alighasemzadeh, any plans or dates for this functionality?

**Comment by aliqasemzadeh** [comment]
@parallels999 I am working on new version.
